name: Build VueJS app

on:
  workflow_run:
    workflows: ["My first action"]
    types:
      - completed

env:
  PWD: ./simple-sap

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Also added names to the steps for clarity
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.PWD }}
      - name: Build App
        run: npm run build
        working-directory: ${{ env.PWD }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.PWD }}
          push: true
          tags: user/app:latest
